apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
  namespace: tools
spec:
  ports:
    - name: vault
      port: 80
      targetPort: 8200
  selector:
    app: vault
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
  namespace: tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: vault
        name: vault
        ports:
        - containerPort: 8200
          protocol: TCP
        securityContext:
         capabilities:
           add:
             - IPC_LOCK 
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: vault-root-token
